//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THDShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DE_BILL
    {
        public int IDBILL { get; set; }
        public int IDORDER { get; set; }
        public int IDPRODUCT { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string NOTE { get; set; }
    
        public virtual BILL BILL { get; set; }
        public virtual DE_ORDER DE_ORDER { get; set; }
    }
}
