//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THDShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.BILLs = new HashSet<BILL>();
            this.DE_ORDER = new HashSet<DE_ORDER>();
        }
    
        public int ID { get; set; }
        public System.DateTime DAY { get; set; }
        public int IDDELIADDRESS { get; set; }
        public double TOTALMONEY { get; set; }
        public string NOTE { get; set; }
        public int STATUS { get; set; }
        public int METHODS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DE_ORDER> DE_ORDER { get; set; }
        public virtual DELI_ADDRESS DELI_ADDRESS { get; set; }
    }
}
